# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
            - name: Obtener repositorio
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Instalar NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 16.18.1
            - name: Verificar instalación NodeJS
              run: node -v
            - name: Instalar Angular CLI
              run: npm install -g @angular/cli@15.1.6
            - name: Instalar dependencias
              run: npm ci
            - name: Verificar instalación Angular CLI y TypeScript
              run: ng version

            - name: Build
              run: ng build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                folder: dist # The folder the action should deploy.
